name: pluto-notebook

on:
    push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.POTATO }}
      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/juliapluto/pluto:latest
      - name: Build and push
        id: build-2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-jupyter
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/juliapluto/pluto-jupyter:latest
